const data = {
    products: [{
        code: 1000,
        name: "Seawalk Winter Zuecos",
        description: "Zuecos con piel. Super livianos",
        price: 1420,
        stock: 100,
        image: "images/winterzuecos.jpg",
        images: ["images/winterzuecos.jpg", "images/winterzuecos1.jpg", "images/winterzuecos2.jpg", "images/winterzuecos3.jpg"],
        size: [19, 20, 21, 22, 23, 24, 25, 26],
        categories: ["invierno", "calzado", "zuecos"],
    }, {
        code: 1001,
        name: "Botin Futsal",
        description: "Botines papi",
        price: 4090,
        stock: 25,
        image: "images/botinpapi.jpg",
        images: ["images/botinpapi.jpg", "images/botinpapi1.jpg"],
        size: [25, 26, 27, 28, 29, 30, 32, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
        categories: ["fubol", "papi", "deporte"],
    }, {
        code: 1002,
        name: "Joggers de gabardina",
        description: "Joggers de gabardina",
        price: 2390,
        stock: 157,
        image: "images/joggers.jpg",
        images: ["images/joggers.jpg", "images/joggers1.jpg", "images/joggers2.jpg", "images/joggers3.jpg", "images/joggers4.jpg"],
        size: [36, 38, 40, 42, 46, 48, 50, 52, 54],
        categories: ["joggers"],
    },{
        code: 1003,
        name: "Camiseta con Botones",
        description: "Camiseta con botones",
        price: 1400,
        stock: 50,
        image: "images/camiseta_bot.jpg",
        images: ["images/camiseta_bot.jpg", "images/camiseta_bot1.jpg", "images/camiseta_bot2.jpg"],
        size: ["S", "M", "L", "XL", "XXL"],
        categories: ["camiseta", "hombre"],
    }, {
        code: 1004,
        name: "Chomba manga larga",
        description: "Chomba manga larga algodon peinado",
        price: 1680,
        stock: 24,
        image: "images/chomba_larga.jpg",
        images: ["images/chomba_larga.jpg"],
        size: ["M", "L", "XL"],
        categories: ["chomba", "hombre"],
    }, {
        code: 1005,
        name: "Campera Algodon",
        description: "Campera algodon peinado frisado",
        price: 2990,
        stock: 23,
        image: "images/campera_alg.jpg",
        images: ["images/campera_alg.jpg", "images/campera_alg1.jpg", "images/campera_alg2.jpg"],
        size: [1, 2, 3, 4, 5],
        categories: ["invinerno", "hombre", "campera"],
    }, {
        code: 1006,
        name: "Sweater tipo bremer",
        description: "Sweater tipo bremer cuello V y redondo",
        price: 1940,
        stock: 5,
        image: "images/sweater_Bremer.jpg",
        images: ["images/sweater_Bremer.jpg", "images/sweater_Bremer1.jpg", "images/sweater_Bremer2.jpg", "images/sweater_Bremer3.jpg", "images/sweater_Bremer4.jpg", "images/sweater_Bremer5.jpg"],
        size: ["M", "L", "XL"],
        categories: ["sweater", "invierno", "hombre"],
    }, {
        code: 1007,
        name: "Zapatillas Jaguar Deportivas",
        description: "Zapatillas Jaguar Deportivas",
        price: 4354,
        stock: 14,
        image: "images/jaguar_deport.jpg",
        images: ["images/jaguar_deport.jpg", "images/jaguar_deport.jpg1"],
        size: [39, 40, 41, 42, 43],
        categories: ["deportes", "zapatillas", "jaguar"],
    },
    ]
}

module.exports = data;